name: Unzip

on:
  push:
    paths:
      - "Inflex_updated.zip"
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Extract zip file
        run: |
          unzip -o Inflex_updated.zip
          rm -rf Inflex_updated.zip

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: unzip and setup InFlex project" || echo "No changes to commit"
          git push
